### ISSUE TITLE
[Marketing-40] Script and video for promoting The Laurel - Spartans and The Force

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#100]
Awarded for the Marketing potential of:
- https://www.youtube.com/watch?v=5XL8ErGtWnQ&feature=youtu.be
- https://www.youtube.com/watch?v=UvyKqDGfDs0&feature=youtu.be

**Comment by onofreicl** [comment]
[CLAIM PROOF]
https://youtu.be/UvyKqDGfDs0
https://youtu.be/5XL8ErGtWnQ
