### ISSUE TITLE
[Intellectual-200] Research and vision for highest concepts associated with The Laurel - Speeches

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#109]
Award for https://github.com/the-laurel/the-laurel-volunteers/blob/7c895a15cc529f14089cfdbecd1802206bd01c50/docs/en/Speeches.md

**Comment by ctzurcanu** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/the-laurel-volunteers/blob/7c895a15cc529f14089cfdbecd1802206bd01c50/docs/en/Speeches.md
