### ISSUE TITLE
[IL-30] Find the equivalent concept/words for "volunteer", from other 2-3 cultures (other than USA)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#11]
"volunteer" is linked to the USA, to the concepts of people "volunteering" to be in the military. They were not volunteers in today's understanding - they had a salary. But they volunteered the risk of losing their lives.

The Laurel should be aware of what other cultures have this concept and what are the words used to denote it.

**Comment by ctzurcanu** [comment]
I'm on this. Thanks for the challenge.

**Comment by ctzurcanu** [comment]
That was fortunate: I found a good name for it, in line with my other work:
https://github.com/the-laurel/the-laurel-volunteers/blob/main/TheOldVolunteer.md

**Comment by ctzurcanu** [comment]
I can guarantee that nobody can make the connections I made in the text without 2 hours of effort (120 Intel Laurels). So I believe I miss 90 IL on this. Thank you.

**Comment by loredanacirstea** [comment]
I will award you the rest on https://github.com/the-laurel/laurels/issues/28
