### ISSUE TITLE
[Marketing-10] Promoting The Laurel Project (Vedlerual)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#128]
Awarded for https://www.linkedin.com/posts/developer787_the-laurel-project-linkedin-activity-6844219041310212096-V3nm/

Usually, a post without personal content is awarded at most 2 laurels. But this is the first post on Linkedin made by a volunteer about The Laurel Project. Scarce resources should be rewarded more.

**Comment by vedlerual** [comment]
[CLAIM PROOF]
https://www.linkedin.com/posts/developer787_the-laurel-project-linkedin-activity-6844219041310212096-V3nm/

**Comment by onofreicl** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/issues/131

**Comment by vedlerual** [comment]
[CLAIM PROOF]
https://www.linkedin.com/posts/developer787_the-laurel-project-linkedin-activity-6845153791927451648-ncT_

**Comment by loredanacirstea** [comment]
[CLAIM PROOF]
Fake Claim
