### ISSUE TITLE
[Marketing-15] Posting and promoting The Laurel on Linkedin

### ISSUE THREAD

**Issue by ctzurcanu** [the-laurel/laurels#129]
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844413697797042176/
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844585625803460608/
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844406042646990848/
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844219041310212096/

**Comment by vedlerual** [comment]
[CLAIM PROOF]
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844413697797042176/
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844585625803460608/
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844406042646990848/
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6844219041310212096/
