### ISSUE TITLE
[Marketing-10] Share about The Laurel Project - first impression, expectations (JRoquette)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#139]
Awarded for https://www.linkedin.com/posts/jroquette_the-laurel-project-linkedin-activity-6845148571671511040-ME4s

**Comment by jroquette** [comment]
[CLAIM PROOF]
https://www.linkedin.com/posts/jroquette_the-laurel-project-linkedin-activity-6845148571671511040-ME4s
