### ISSUE TITLE
[Intellectual-60] The Laurel - Elevation Games (Christian)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#175]

**Comment by ctzurcanu** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/the-laurel-volunteers/commit/ad16cc61c908d005889a94bdd425e005fa776df4
https://github.com/the-laurel/the-laurel-volunteers/commit/fc238fb2c0272b67b455a3b307f2e66493871825
