### ISSUE TITLE
[Coding-20] Fix bug in monitor for showing task url for closed GitHub issues (ghassanmas)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#186]
Awarded for https://github.com/provable-dev/monitoring-bot/pull/20

**Comment by ghassanmas** [comment]
[CLAIM PROOF]
https://github.com/provable-dev/monitoring-bot/pull/20

**Comment by ghassanmas** [comment]
[CLAIM PROOF]
https://github.com/provable-dev/monitoring-bot/pull/20
