### ISSUE TITLE
[Marketing-10] Promoting The Laurel Project & tools (5 RTs, Sept 28) (incredulous)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#190]
Awarded for 5 RTs today on https://twitter.com/prix____/with_replies.

**Comment by increDul0us** [comment]
[CLAIM PROOF]
1. https://www.reddit.com/r/provable_laurel/comments/pt3vus/comment/helnng1/?utm_source=share&utm_medium=web2x&context=3
2. https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/helmuhy/?utm_source=share&utm_medium=web2x&context=3
3. https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/helmscn/?utm_source=share&utm_medium=web2x&context=3

**Comment by increDul0us** [comment]
[CLAIM PROOF]
1. https://www.reddit.com/r/provable_laurel/comments/pt3vus/comment/helnng1/?utm_source=share&utm_medium=web2x&context=3
2. https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/helmuhy/?utm_source=share&utm_medium=web2x&context=3
3. https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/helmscn/?utm_source=share&utm_medium=web2x&context=3

**Comment by increDul0us** [comment]
[CLAIM PROOF]
https://twitter.com/prix____

**Comment by increDul0us** [comment]
[CLAIM PROOF]
https://twitter.com/prix____

**Comment by increDul0us** [comment]
[CLAIM PROOF]
https://twitter.com/prix____
