### ISSUE TITLE
[Marketing-10] Commenting on The Laurel Project and Tools (Reddit)

### ISSUE THREAD

**Issue by vedlerual** [the-laurel/laurels#195]
Upvote.

**Comment by increDul0us** [comment]
[CLAIM PROOF]
https://www.reddit.com/r/provable_laurel/comments/pxv90j/comment/hew3el5/?utm_source=share&utm_medium=web2x&context=3

**Comment by increDul0us** [comment]
[CLAIM PROOF]
https://twitter.com/prix____
