### ISSUE TITLE
[Marketing-10] Promoting The Laurel Project and Tools - 5 RTs (IceDragon)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#198]
Awarded for https://twitter.com/0xpapa

**Comment by 0xpapa** [comment]
[CLAIM PROOF]
https://twitter.com/0xpapa

**Comment by 0xpapa** [comment]
[CLAIM PROOF]
https://twitter.com/0xpapa

**Comment by 0xpapa** [comment]
[CLAIM PROOF]
https://twitter.com/0xpapa
