### ISSUE TITLE
[Marketing-10] Promoting The Laurel Project & tools - 5 RTs (OneEyeDoll)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#203]
Awarded for https://twitter.com/oneeyedoll

**Comment by OneEyeDoll** [comment]
[CLAIM PROOF]
https://twitter.com/oneeyedoll

**Comment by OneEyeDoll** [comment]
[CLAIM PROOF]
https://twitter.com/oneeyedoll

**Comment by OneEyeDoll** [comment]
[CLAIM PROOF]
twitter.com/oneeyedoll
