### ISSUE TITLE
[Intellectual-60] Hierarchy of generosity - theory update (Christian)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#213]
Awarded for https://github.com/the-laurel/the-laurel-volunteers/commit/2157ebdea348c40b4b7dacfcdd314a1f15395e7f

**Comment by ctzurcanu** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/the-laurel-volunteers/commit/2157ebdea348c40b4b7dacfcdd314a1f15395e7f
