### ISSUE TITLE
[Guard-90] Guard the chat for questions & tasks (Vedlerual) (25sept-1oct)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#218]
Awarded for:
https://discord.com/channels/863542354119360525/863542354119360528/891706915799855125
https://discord.com/channels/863542354119360525/865156500188168213/892160601122541600

**Comment by vedlerual** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/issues/218
