### ISSUE TITLE
[Language Translations-25] Translation from En to Sw of The Laurel Code of Conduct (IceDragon)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#223]
Translation from En to Sw of https://github.com/the-laurel/laurels/blob/main/docs/en/CodeOfConduct.md

**Comment by 0xpapa** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/pull/222

**Comment by 0xpapa** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/pull/222

**Comment by 0xpapa** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/pull/222
