### ISSUE TITLE
[Marketing-10] Promoting The Laurel Project & tools (SuyashMane)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#253]

**Comment by SuyashMane** [comment]
[CLAIM PROOF]
https://www.linkedin.com/feed/update/urn:li:activity:6851846613053386752/
https://www.facebook.com/suyash.mane.16/posts/4593852840653483
https://twitter.com/Suyash_V_Mane/status/1446057372829446148
