### ISSUE TITLE
[Marketing-10] Linkedin intro post for The Laurel Project (Pedro)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#288]
Awarded for https://www.linkedin.com/feed/update/urn:li:activity:6860320508001472514/

**Comment by PedroMarianoAlmeida** [comment]
[CLAIM PROOF]
https://mark.provable.dev/?ipfs=QmXcsaUDCQDvGQiZnnJtxiuAPe2DgSbxa4dr1XUtnmTjLu&issue=288
