### ISSUE TITLE
[Marketing-26] Promoting The Laurel - retweets, likes, shares (Hazem)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#290]
- 14 shares/reactions on Linkedin
- 17 retweets & 23 likes for @provable_laurel twitter
- 25 retweets & 25 likes for @lorecirstea twitter

**Comment by hazem-saeed** [comment]
[CLAIM PROOF]
https://twitter.com/HazemSaeedDev

**Comment by hazem-saeed** [comment]
[CLAIM PROOF]
https://github.com/hazem-saeed
