### ISSUE TITLE
[Marketing-10] 5 questions about The Laurel Project - Reddit (Pedro)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#291]
Awarded for: 
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirl7c7/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirlmbx/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirm6g8/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hiror2q/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirobac/?context=3

**Comment by PedroMarianoAlmeida** [comment]
[CLAIM PROOF]
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirl7c7/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirlmbx/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirm6g8/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hiror2q/?context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/hirobac/?context=3

**Comment by PedroMarianoAlmeida** [comment]
[CLAIM PROOF]
 https://mark.provable.dev/?ipfs=QmXcsaUDCQDvGQiZnnJtxiuAPe2DgSbxa4dr1XUtnmTjLu&issue=291

**Comment by PedroMarianoAlmeida** [comment]
[CLAIM PROOF]
https://mark.provable.dev/?ipfs=QmXcsaUDCQDvGQiZnnJtxiuAPe2DgSbxa4dr1XUtnmTjLu&issue=291

**Comment by PedroMarianoAlmeida** [comment]
[CLAIM PROOF]
https://mark.provable.dev/?ipfs=QmXcsaUDCQDvGQiZnnJtxiuAPe2DgSbxa4dr1XUtnmTjLu&issue=291
