### ISSUE TITLE
[Coding-10] Setting up a free tier Heroku account & email & donating to The Laurel Project (Hazem)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#297]
This task will be 2*10=20 laurels. I will also claim it on behalf of the volunteer.

**Comment by loredanacirstea** [comment]
[CLAIM PROOF]
Account credentials have been given to the project: laurel_project@protonmail.com

**Comment by hazem-saeed** [comment]
[CLAIM PROOF]
https://github.com/hazem-saeed
