### ISSUE TITLE
[Marketing-10] Ask 5 questions about The Laurel Project on Reddit (rramirez)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#299]
Asked in https://www.reddit.com/r/provable_laurel/comments/pt3opa/the_laurel_project_and_protocol_qa/

**Comment by rodrigoramirez93** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/issues/299

**Comment by rodrigoramirez93** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/issues/299

**Comment by rodrigoramirez93** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/issues/299
