### ISSUE TITLE
[Coding-60] Work on the onboarding guides (Pedro)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#303]
This is a 120 laurels task, but I will claim it on Pedro's behalf, so it will count as 2*60 = 120 laurels.

**Comment by loredanacirstea** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/marks/pull/1
https://github.com/the-laurel/marks/pull/2

**Comment by PedroMarianoAlmeida** [comment]
[CLAIM PROOF]
https://marks.provable.dev/?contentUrl=https://raw.githubusercontent.com/the-laurel/marks/main/guides/SetUp.md
