### ISSUE TITLE
[Marketing-10] Asking 5 questions about the protocol on Reddit (CjnapoleaoUS)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#321]

**Comment by cnapolea** [comment]
[CLAIM PROOF]
https://www.reddit.com/user/Huge_Department_3004/

**Comment by cnapolea** [comment]
[CLAIM PROOF]
https://www.reddit.com/user/Huge_Department_3004/
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hk9alt9/?utm_source=share&utm_medium=web2x&context=3
