### ISSUE TITLE
[Marketing-10] First sight feedback on Reddit (Taha)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#328]

**Comment by TahaMalas** [comment]
[CLAIM PROOF]
https://www.reddit.com/r/provable_laurel/comments/pt3vus/comment/hklk95k/?utm_source=share&utm_medium=web2x&context=3

**Comment by defnlife** [comment]
[CLAIM PROOF]
https://www.reddit.com/r/provable_laurel/comments/pt3vus/at_first_sight_no1/hlolyel/
