### ISSUE TITLE
[Coding-240] Transpiler for Taylor to use indents (like Python), with optional parens (Christian)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#331]

**Comment by ctzurcanu** [comment]
[CLAIM PROOF]
https://github.com/loredanacirstea/ark/pull/71

**Comment by theallegrarr** [comment]
[CLAIM PROOF]
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1iwus/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1irmt/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1igu4/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1ie51/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1i5vh/?utm_source=share&utm_medium=web2x&context=3
