### ISSUE TITLE
[Marketing-10] Ask 5 questions on Reddit about The Laurel Project (theallegrarr)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#332]

**Comment by theallegrarr** [comment]
[CLAIM PROOF]
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1i5vh/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1ie51/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1igu4/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1irmt/?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/provable_laurel/comments/pt3opa/comment/hl1iwus/?utm_source=share&utm_medium=web2x&context=3
