### ISSUE TITLE
[Marketing-10] Tweet an honest post about The Laurel Project (Satvika)

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#352]

**Comment by SatvikaVyas** [comment]
[CLAIM PROOF]
https://twitter.com/satvika33777668/status/1468884924463648768

**Comment by SatvikaVyas** [comment]
[CLAIM PROOF]
https://twitter.com/satvika33777668/status/1468884924463648768

**Comment by SatvikaVyas** [comment]
[CLAIM PROOF]
https://twitter.com/satvika33777668/status/1468884924463648768
