### ISSUE TITLE
[Technical Writing-320] Ideas for EDS Applications

### ISSUE THREAD

**Issue by ctzurcanu** [the-laurel/laurels#382]
https://github.com/loredanacirstea/ideas/tree/main/CT

**Comment by ctzurcanu** [comment]
[CLAIM PROOF]
https://github.com/loredanacirstea/ideas/tree/main/CT

**Comment by loredanacirstea** [comment]
[CLAIM PROOF]
https://github.com/loredanacirstea/ideas/commits?author=ctzurcanu&since=2021-12-6T00:00:00Z&until=2021-12-14T23:59:59Z
