### ISSUE TITLE
[Marketing-10] Posting 8 tweets about The Laurel - Claudiu

### ISSUE THREAD

**Issue by loredanacirstea** [the-laurel/laurels#98]
Awarded for:
https://twitter.com/_ClaudiuOnofrei/status/1429920510918418438
https://twitter.com/_ClaudiuOnofrei/status/1430458972016975877
https://twitter.com/_ClaudiuOnofrei/status/1430282948209750021
https://twitter.com/_ClaudiuOnofrei/status/1430274223465971715
https://twitter.com/_ClaudiuOnofrei/status/1430282948209750021
https://twitter.com/_ClaudiuOnofrei/status/1430825514743255040
https://twitter.com/_ClaudiuOnofrei/status/1431020629956964352
https://twitter.com/_ClaudiuOnofrei/status/1430782113729630208

**Comment by onofreicl** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/issues/98

**Comment by onofreicl** [comment]
[CLAIM PROOF]
https://github.com/the-laurel/laurels/issues/98
